dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - unzip
      - libx11-dev
      - libfreetype6
      - libfreetype6-dev
cache:
  directories:
  - $TRAVIS_BUILD_DIR/deps
script:
  # Link gcc-8 and g++-8 to their standard commands
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  # Get newest cmake
  - sudo apt remove cmake
  - sudo apt-get purge cmake
  - mkdir temp
  - cd temp
  - wget https://cmake.org/files/v3.11/cmake-3.11.4.tar.gz
  - tar -xzf cmake-3.11.4.tar.gz
  - cd cmake-3.11.4/
  - ./bootstrap
  - make
  - sudo make install
  - cd ..
  - cd ..
  # Run your build commands next
  - mkdir build
  - cd build
  - /usr/local/bin/cmake  ..
  - make
  - /usr/local/bin/cpack -G DEB
